const carData = [
  {
    brand: "maruti",
    model: "Baleno",
    location: "Bangalore",
    colour: "Blue",
    numberOfOwners: 3,
    yearOfManufacture: "2017",
    transmission: "manual",
    insuranceValidUpto: "2021",
    externalFitments: "",
    kms: "50000",
    budget: 230000,
    photo:
      "https://cloudfront.timesnownews.com/media/new-bolder-baleno-5_45954180415_o.jpg",
  },
  {
    brand: "Tata",
    model: "Altroz",
    location: "chennai",
    colour: "Gold",
    numberOfOwners: 1,
    yearOfManufacture: "2018",
    transmission: "automatic",
    insuranceValidUpto: "2022",
    externalFitments: "",
    kms: "50000",
    budget: 300000,
    photo: "https://www.ccarprice.com/products/Tata_Altroz_2023_1.jpg",
  },
  {
    brand: "kia",
    model: "carnivel",
    location: "Bangalore",
    colour: "DarkBlue",
    numberOfOwners: 2,
    yearOfManufacture: "2015",
    transmission: "automatic",
    insuranceValidUpto: "2021",
    externalFitments: "",
    kms: "520000",
    photo:
      "https://images.summitmedia-digital.com/topgear/images/2022/02/17/kia-carnival-2022-main-1645087148.jpg",
  },
  {
    brand: "Mahindra",
    model: "XUV400",
    location: "Bangalore",
    colour: "white",
    numberOfOwners: 2,
    yearOfManufacture: "2017",
    transmission: "automatic",
    insuranceValidUpto: "2022",
    externalFitments: "",
    kms: "900000",
    photo:
      "https://ik.imagekit.io/parkplus/production/chariot_staging/public/frontleftside47jpgimage_20230808201051421202.jpg",
  },
];
export default carData;
